### ISSUE TITLE
ValueError: Shape must be rank 2 but is rank 3 for 'seq2seq/sentiment_layer/MatMul' (op: 'MatMul') with input shapes: [8,10,1029], [1029,256].

### ISSUE THREAD

**Issue by mokeeqian** [dengyang17/OAAG#2]
Hi, thanks for offering your implement for the OAAG model.

I got this error while running it:

```
Traceback (most recent call last):
  File "/code/oaag-static/run_summarization.py", line 347, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/code/oaag-static/run_summarization.py", line 336, in main
    setup_training(model, batcher, vocab, hps)
  File "/code/oaag-static/run_summarization.py", line 163, in setup_training
    model.build_graph() # build the graph
  File "/code/oaag-static/model.py", line 480, in build_graph
    self._add_seq2seq()
  File "/code/oaag-static/model.py", line 372, in _add_seq2seq
    self.y_prob, self.y_pred, self.review_attention, decode_in_state = self._self_matching(sentiment_input, hps.batch_size)

  File "/code/oaag-static/model.py", line 292, in _self_matching
    U = tf.tanh(tf.matmul(sentiment_input, W))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py", line 2455, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 5333, in mat_mul
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 2 but is rank 3 for 'seq2seq/sentiment_layer/MatMul' (op: 'MatMul') with input shapes: [8,10,1029], [1029,256].
```
It seems that the `sentiment_input` and `W` are not at the same shape, could you please tell me how to fix it?

**Comment by dengyang17** [comment]
I think it is due to the tensorflow version. It may be similar to this issue [https://github.com/ACL2020SpellGCN/SpellGCN/issues/22](url).

**Comment by mokeeqian** [comment]
> I think it is due to the tensorflow version. It may be similar to this issue [https://github.com/ACL2020SpellGCN/SpellGCN/issues/22](url).

okey, thank you a lot! I've already fix it.

By the way, the Baseline models that your paper mentioned like **S2SA**, **S2SAR**, **RAGE**, etc. would you like to share me a copy of code? (because I don't know how to modify the original models to fit the data format from your paper.)

I would appreciate you if possible.

Have A Nice Day!
